# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=100)),
                ('descripcionCategoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreColor', models.CharField(max_length=100)),
                ('descripcionColor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=100)),
                ('descripcionProducto', models.CharField(max_length=100)),
                ('referenciaProducto', models.CharField(max_length=50)),
                ('cantidadProducto', models.IntegerField(default=0)),
                ('precioProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoriaProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Categoria')),
                ('colorProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTalla', models.CharField(max_length=100)),
                ('descripcionTalla', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tallaProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Talla'),
        ),
    ]
